name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

jobs:
  check-fish:
    name: Check Fish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.launchpad.net:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@01908efef0271aea4875ed31f316c4c4e25ad49b # v2.0.28
      - uses: fish-shop/indent-check@08eef5741a347581e53126fd38b37b15feaa017a # v2.2.74
      - uses: fish-shop/syntax-check@891b4226c0718d4e055c7bebb1e1936430809b04 # v2.2.73
      - uses: fish-shop/install-plugin@f5d4eff26aff58081c0c8c8cc5ef90805efa5ba9 # v2.3.76
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@394b64226c9843f737b233d7dc06cf024399b7b6 # v2.3.76
